# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in factory_bot-blueprint-rspec.gemspec
gemspec

gem "factory_bot-blueprint", path: "../factory_bot-blueprint"
gem "factrey", path: "../factrey"
gem "rake", "~> 13.0", require: false
gem "rspec", "~> 3.0", require: false
gem "rubocop", "~> 1.63", require: false
gem "rubocop-rspec", "~> 2.29", require: false

group :test do
  gem "test-prof", "~> 1.0"
end
