# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in factrey.gemspec
gemspec

gem "factrey", path: "../factrey"
gem "rake", "~> 13.0", require: false
gem "rspec", "~> 3.0", require: false
gem "rubocop", "~> 1.63", require: false
gem "rubocop-factory_bot", "~> 2.26", require: false
gem "rubocop-rspec", "~> 3.2", require: false
